language: node_js
node_js:
- '6.9'
branches:
  only:
  - master
  - stable
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod
after_success:
- firebase deploy --token $FIREBASE_TOKEN
before_install:
- openssl aes-256-cbc -K $encrypted_946c8013f8fc_key -iv $encrypted_946c8013f8fc_iv
  -in ./src/app/firebase-config.ts.enc -out ./src/app/firebase-config.ts -d
