language: node_js
node_js:
  - "6.9"

branches:
  only:
  - master
  - stable

before_script:
  - npm install -g vue-cli
  - npm install -g firebase-tools

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN